amazon-contributing/opentelemetry-collector-contrib

- receiver/awscontainerinsightreceiver/README.md
- receiver/awscontainerinsightreceiver/config.go
- receiver/awscontainerinsightreceiver/config_test.go
- receiver/awscontainerinsightreceiver/factory.go
- receiver/awscontainerinsightreceiver/internal/ecsInfo/ecs_instance_info.go
- receiver/awscontainerinsightreceiver/internal/ecsInfo/ecs_instance_info_test.go
- receiver/awscontainerinsightreceiver/internal/ecsInfo/ecsinfo.go
- receiver/awscontainerinsightreceiver/internal/ecsInfo/ecsinfo_test.go
- receiver/awscontainerinsightreceiver/internal/host/hostinfo.go
- receiver/awscontainerinsightreceiver/internal/host/hostinfo_test.go
- receiver/awscontainerinsightreceiver/receiver.go
- receiver/awscontainerinsightreceiver/testdata/config.yaml
Description: Add config option to override cluster name. This is to maintain backwards compatibility to CloudWatchAgent where customers have the option to specify a cluster name via the config.
Testing: Unit tests added/updated to test config option
Documentation: Updated README.md
> [receiver/awscontainerinsightreceiver] Add option to override cluster name

- receiver/awscontainerinsightreceiver/README.md
- receiver/awscontainerinsightreceiver/config.go
- receiver/awscontainerinsightreceiver/factory.go
- receiver/awscontainerinsightreceiver/internal/stores/store.go
- receiver/awscontainerinsightreceiver/internal/stores/utils.go
- receiver/awscontainerinsightreceiver/internal/stores/utils_test.go
- receiver/awscontainerinsightreceiver/receiver.go
**Description:** Add option for adding container name as a metric label. Currently, the container name tag/label is copied over to the kubernetes blob and there is no way to retain it as a label.
Example:
```
{
"AutoScalingGroupName": "eks-cw1-ng-5ec244c0-bedf-d668-e90c-18064cc7c293",
"ClusterName": "cw_gpu",
"InstanceId": "i-0e1104896e4b76eb8",
"InstanceType": "t3.small",
"Namespace": "kube-system",
"NodeName": "ip-192-168-228-23.ec2.internal",
"PodName": "kube-proxy",
"Sources": [
"cadvisor",
"pod",
"calculated"
],
"Timestamp": "1682460806199",
"Type": "Container",
"Version": "0",
"container_cpu_request": 100,
"container_cpu_usage_system": 0.2375214653312615,
"container_cpu_usage_total": 0.44476191624426764,
"container_cpu_usage_user": 0.1357265516178637,
"container_cpu_utilization": …
```
> [receiver/awscontainerinsightreceiver] Add option for adding container name as a metric label

- exporter/awsemfexporter/metric_translator.go
- exporter/awsemfexporter/metric_translator_test.go
**Description:** Always set Timestamp & Version for EMF v0 - even for non-EMF log events
* Example of existing non-EMF log event from CWA EKS CI:
```
{
"AutoScalingGroupName": "eks-cw1-ng-5ec244c0-bedf-d668-e90c-18064cc7c293",
"ClusterName": "cwa1",
"InstanceId": "i-0e1104896e4b76eb8",
"InstanceType": "t3.small",
"NodeName": "ip-192-168-228-23.ec2.internal",
"Sources": [
"cadvisor",
"calculated"
],
"Timestamp": "1683149073064",
"Type": "NodeNet",
"Version": "0",
"interface": "eth0",
"kubernetes": {
"host": "ip-192-168-228-23.ec2.internal"
},
"node_interface_network_rx_bytes": 3488.2609543812264,
"node_interface_network_rx_dropped": 0,
"node_interface_network_rx_errors": 0,
"node_interface_network_rx_packets": 15.266481881592593,
"node_interface_network_total_bytes": 8031.807898565579, …
```
> [exporter/awsemfexporter] Always set Timestamp & Version for EMF v0

- internal/aws/containerinsight/const.go
- internal/aws/k8s/k8sclient/clientset.go
- internal/aws/k8s/k8sclient/clientset_test.go
- internal/aws/k8s/k8sclient/node.go
- internal/aws/k8s/k8sclient/node_info.go
- internal/aws/k8s/k8sclient/node_test.go
- receiver/awscontainerinsightreceiver/README.md
- receiver/awscontainerinsightreceiver/internal/stores/nodeinfo.go
- receiver/awscontainerinsightreceiver/internal/stores/nodeinfo_test.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore_test.go
- receiver/awscontainerinsightreceiver/internal/stores/utils_test.go
This change introduces new node level metrics that help understand the status of a node. Precisely, the new metrics are:
* node_status_condition_ready
* node_status_condition_pid_pressure
* node_status_condition_memory_pressure
* node_status_condition_disk_pressure
* node_status_capacity_pods
* node_status_allocatable_pods
These metrics are typically consumed by customers at two aggregation levels: at a cluster level and at a node level. Customers can do this by specifying two dimension sets in their [awsemfexporter's](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter) `metric_declaration` config corresponding to `[ClusterName]` and `[ClusterName, InstanceId, NodeName]`.
This code while running on each node in the cluster queries the …
> [receiver/awscontainerinsightreceiver] Add new node level status metrics

- internal/aws/containerinsight/const.go
- internal/aws/containerinsight/utils.go
- internal/aws/k8s/k8sclient/clientset.go
- internal/aws/k8s/k8sclient/daemonset.go
- internal/aws/k8s/k8sclient/daemonset_info.go
- internal/aws/k8s/k8sclient/daemonset_test.go
- internal/aws/k8s/k8sclient/deployment.go
- internal/aws/k8s/k8sclient/deployment_info.go
- internal/aws/k8s/k8sclient/deployment_test.go
- receiver/awscontainerinsightreceiver/README.md
- receiver/awscontainerinsightreceiver/internal/k8sapiserver/k8sapiserver.go
- receiver/awscontainerinsightreceiver/internal/k8sapiserver/k8sapiserver_test.go
**Description:** Add new deployment and daemon set metrics for EKS Container Insights.
* Precisely, the following are the new metrics:
```
deployment_spec_replicas
deployment_status_replicas
deployment_status_replicas_available
deployment_status_replicas_unavailable
daemonset_status_number_available
daemonset_status_number_unavailable
daemonset_status_desired_number_scheduled
daemonset_status_current_number_scheduled
```
* These new metrics are scraped as part of the `k8sapiserver` logic - meaning these are extracted by making calls to the k8s api server. Since these are collected for the whole cluster and should be done only once, this code gets executed only on the leader node's code path.
* Note that for the service account running the agent/collector pod, the role its bound to should …
> [receiver/awscontainerinsightreceiver] Add new deployment and daemonset metrics

- internal/aws/awsutil/awsconfig.go
- internal/aws/awsutil/conn.go
- internal/aws/awsutil/conn_test.go
- receiver/awscontainerinsightreceiver/config.go
- receiver/awscontainerinsightreceiver/internal/host/hostinfo.go
- receiver/awscontainerinsightreceiver/internal/host/hostinfo_test.go
- receiver/awscontainerinsightreceiver/receiver.go
Add Profile And Shared Credentials File To AWS Session Settings
Add feature, 
turn on container insights if aws session region is passed in
allow configuring profile and shared creds via exporter config. 
internal ticket
**Testing:** 
Confirmed metrics and logs are published to cw when running minikube on my mac. While mounting the creds file. 
Config
```
exporters:
awsemf/containerinsights:
detailed_metrics: false
dimension_rollup_option: NoDimensionRollup
eks_fargate_container_insights_enabled: false
endpoint: ""
local_mode: false
log_group_name: /aws/containerinsights/{ClusterName}/performance
log_retention: 0
log_stream_name: '{NodeName}'
max_retries: 2
metric_declarations:
- dimensions:
- - ClusterName
- Namespace
- PodName
- - …
```
> Get AWS Session From Config awscontainerinsightreceiver

- exporter/prometheusexporter/collector_test.go
- exporter/prometheusexporter/prometheus_test.go
- pkg/translator/prometheus/README.md
- pkg/translator/prometheus/normalize_name.go
- pkg/translator/prometheus/normalize_name_test.go
- pkg/translator/prometheusremotewrite/number_data_points_test.go
- receiver/prometheusreceiver/metrics_receiver_helper_test.go
- receiver/prometheusreceiver/metrics_receiver_honor_timestamp_test.go
- receiver/prometheusreceiver/metrics_receiver_metric_name_normalize_test.go
- receiver/prometheusreceiver/metrics_receiver_non_numerical_test.go
- receiver/prometheusreceiver/metrics_receiver_test.go
- receiver/prometheusreceiver/metrics_reciever_metric_rename_test.go
**Description:** This is a follow up to https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/28 where an upstream change (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20518) enabled a feature to normalize metric names by default.
This causes a test failure on our end and in order to mitigate that and bring us back to a stable state, reverting this change to disable this feature by default.
**Testing:** Relying on build checks & tests.
> [receiver/prometheus] Disable pkg.translator.prometheus.NormalizeName by default

- receiver/awscontainerinsightreceiver/internal/host/ec2metadata.go
- receiver/awscontainerinsightreceiver/internal/host/ec2metadata_test.go
- receiver/awscontainerinsightreceiver/internal/host/hostinfo.go
- receiver/awscontainerinsightreceiver/internal/host/hostinfo_test.go
Feature: when running in local mode no need to try. to get ec2 metadata
Internal sim
**Testing:** 
Took in private cwa. Made sure the error for not getting was not in log. 
**Documentation:** 
N/A
> Do Not Refresh EC2 Tags For Local Mode

- internal/aws/containerinsight/const.go
- internal/aws/containerinsight/utils.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore_test.go
- receiver/awscontainerinsightreceiver/internal/stores/test_resources/all_pod_conditions_valid.json
- receiver/awscontainerinsightreceiver/internal/stores/test_resources/one_pod_condition_invalid.json
- receiver/awscontainerinsightreceiver/internal/stores/test_resources/pod_in_phase_failed.json
- receiver/awscontainerinsightreceiver/internal/stores/test_resources/pod_in_phase_pending.json
- receiver/awscontainerinsightreceiver/internal/stores/test_resources/pod_in_phase_running.json
- receiver/awscontainerinsightreceiver/internal/stores/test_resources/pod_in_phase_succeeded.json
- receiver/awscontainerinsightreceiver/internal/stores/test_resources/pod_in_phase_unknown.json
Emit 8 new kube_pod_status_* metrics for containerinsights
- pod_status_running
- pod_status_pending
- pod_status_succeeded
- pod_status_failed
- pod_status_unknown
- pod_status_ready
- pod_status_scheduled
- pod_status_initialized
1. Unit test
2. Made changes to the Cloudwatch Agent code, and verified this data gets emitted as emf log (metrics on dashboard were also tested, but that will be described in the cloudwatch agent code commits.)
> Emit 8 new pod_status_* metrics for containerinsights

- exporter/awsxrayexporter/internal/translator/aws.go
- exporter/awsxrayexporter/internal/translator/aws_test.go
The X-Ray SDK already sets the SDK name as `X-Ray for Go`, so the function in the awsxrayexporter is appending an additional "for Go" at the end.
Current implementation results in:
```
"aws": {
"xray": {
"auto_instrumentation": false,
"sdk_version": "1.8.1",
"sdk": "X-Ray for Go for Go"
}
},
```
The change checks to see if it has the suffix already and skips the append if it does.
**Testing:** Added unit test.
> Fix repeated append of SDK language

- exporter/awsxrayexporter/internal/translator/segment.go
- exporter/awsxrayexporter/internal/translator/segment_test.go
The X-Ray receiver marshals the metadata from the X-Ray SDK, but the exporter doesn't unmarshal the metadata, which results in squashed and incorrectly nested metadata. See issue for examples.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23610
**Testing:** Added unit tests.
> Fix X-Ray metadata unmarshaling

- exporter/awsxrayexporter/awsxray.go
- internal/aws/xray/telemetry/sender.go
- internal/aws/xray/telemetry/sender_test.go
**Description:** If the configuration for the awsxrayexporter has `LocalMode` set to true, the telemetry collection should respect it and skip the IMDS calls.
> LocalMode – Set to true to skip checking for EC2 instance metadata.
https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-configuration.html
**Testing:** Added unit tests. Fix broken unit test from https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/33
> Skip IMDS calls for X-Ray telemetry if in LocalMode.

- config/confighttp/confighttp.go
Omit TLS settings to remove panic from null pointer
Marshalling this leads to the config.yaml having redacted certs for the resource detection processor, which causes the agent to panic from a null pointer exception.
> omit TLS client setting

- receiver/awscontainerinsightreceiver/internal/stores/podstore.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore_test.go
- receiver/awscontainerinsightreceiver/internal/stores/store.go
- receiver/awscontainerinsightreceiver/receiver.go
The enhanced metric feature was emitting extra data to the EMF logs even when the enhanced feature (granularity 2+) was not enabled.  The metrics weren't being enabled but there was concern that the extra data could impact customers bills.  This is a two-way door that can be enabled in line with any potential "enhanced" feature changes
Basically I introduced a new flag `includeEnhancedMetrics` that is only set when control plane metrics is set
This does add extra nesting / wrapping in the middle of methods.  Another option would be to create some sort of filter that is executed after each loop
**Testing:** 
I ran the latest on my test cluster and confirmed we are collecting less data:
diff:
```
4c4
<     "InstanceId": "i-092efe5a5dcb6bb29", …
```
> do not emit enhanced metrics unless we are already emitting control plane metrics

- receiver/awscontainerinsightreceiver/README.md
Update README with updated suggestion for ClusterRole rules
**Testing:** I deployed the following and I confirmed the expected metrics were still flowing in my test cluster
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: cloudwatch-agent-role
rules:
- apiGroups: [""]
resources: ["pods", "nodes", "endpoints"]
verbs: ["list", "watch"]
- apiGroups: ["apps"]
resources: ["replicasets", "daemonsets", "deployments"]
verbs: ["list", "watch"]
- apiGroups: ["batch"]
resources: ["jobs"]
verbs: ["list", "watch"]
- apiGroups: [""]
resources: ["nodes/proxy"]
verbs: ["get"]
- apiGroups: [""]
resources: ["nodes/stats", "configmaps", "events"]
verbs: ["create"]
- apiGroups: [""]
resources: ["configmaps"]
resourceNames: ["cwagent-clusterleader"]
verbs: …
```
> update readme with suggested ClusterRole rules

- internal/aws/metrics/metric_calculator.go
- internal/aws/metrics/metric_calculator_test.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore_test.go
Bug fix
The following crash was reported
```
fatal error: concurrent map iteration and map write
goroutine 144 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/internal/aws/metrics.(*MapWithExpiry).CleanUp(...)
github.com/open-telemetry/opentelemetry-collector-contrib/internal/aws/metrics@v0.77.0/metric_calculator.go:134
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver/internal/stores.(*PodStore).cleanup(0xc0002ae620, {0x4ad45b0?, 0xc0003cb600?, 0x6d0fc40?})
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver@v0.77.0/internal/stores/podstore.go:279 +0x299
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver/internal/stores.( …
```
> fix concurrent map write crash in podstore

- exporter/datadogexporter/internal/hostmetadata/internal/ec2/ec2.go
- internal/aws/awsutil/conn.go
- internal/aws/proxy/conn.go
- internal/aws/xray/telemetry/sender.go
- internal/metadataproviders/aws/ec2/metadata.go
- receiver/awscontainerinsightreceiver/internal/host/ec2metadata.go
Was not calling imdsv1 when retryer was enabled. 
N/A
**Testing:** 
Tried using the private agent. 
**Documentation:** 
N/A
> Do Not Try To Retry For IMDS V1

- internal/aws/containerinsight/const.go
- receiver/awscontainerinsightreceiver/README.md
- receiver/awscontainerinsightreceiver/internal/stores/podstore.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore_test.go
- receiver/awscontainerinsightreceiver/internal/stores/test_resources/pod_Ready_Scheduled_Condition_Unknown.json
Adding pod_status_unknown as a Pod condition metric and removed the pod_status_initialized metric
Unit testing and Manual testing deploying the docker image on cluster
Sample CW log 
```{
"AutoScalingGroupName": "eks-ng-9ba60313-0ec4c7bb-39c4-ad98-f12c-889c817b9234",
{
[
"ClusterName",
"Namespace",
"PodName"
],
[
"ClusterName"
],
[
"ClusterName",
"FullPodName",
"Namespace",
"PodName"
]
],
"Metrics": [
{
"Name": "pod_status_scheduled"
},
{
"Name": "pod_status_ready"
},
{
"Name": "pod_number_of_containers",
"Unit": "Count"
},
{
"Name": …
```
> Adding pod_status_unknown as a Pod condition metric and removed the pod_status_initialized metric

- internal/aws/containerinsight/const.go
- receiver/awscontainerinsightreceiver/README.md
- receiver/awscontainerinsightreceiver/internal/stores/nodeinfo.go
- receiver/awscontainerinsightreceiver/internal/stores/nodeinfo_test.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore_test.go
Added node_status_condition_unknown metric
Unit testing and manual testing on EKS cluster
Log Event
```
{
"AutoScalingGroupName": "eks-ng-9ba60313-0ec4c7bb-39c4-ad98-f12c-889c817b9234",
{
[
"ClusterName",
"InstanceId",
"NodeName"
],
[
"ClusterName"
]
],
"Metrics": [
{
"Name": "node_memory_utilization",
"Unit": "Percent"
},
{
"Name": "node_memory_reserved_capacity",
"Unit": "Percent"
},
{
"Name": "node_number_of_running_pods",
"Unit": "Count"
},
{
"Name": "node_number_of_running_containers",
"Unit": "Count"
},
{
"Name": …
```
> Node status condition unknown metric

- pkg/stanza/fileconsumer/config.go
- pkg/stanza/fileconsumer/reader_factory.go
- pkg/stanza/fileconsumer/reader_test.go
- pkg/stanza/fileconsumer/splitter_factory.go
- pkg/stanza/operator/helper/encoding.go
- pkg/stanza/operator/helper/splitter.go
- pkg/stanza/operator/input/tcp/tcp.go
- pkg/stanza/operator/input/udp/udp.go
**Description:** The shared buffer in the stanza decoder was causing a concurrency issue where the buffer would get updated by multiple separate threads. This meant that some messages were getting corrupted after decoding and some messages were getting completely replaced. This resulted in duplicates and invalid logs getting passed through the collector.
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24980
**Testing:** Reproduced the issue with a generator that established multiple TCP connections and sent to the tcplogreceiver concurrently. No longer seeing the issue after changing the `helper.Encoding` instantiation to each thread instead of using a shared one.
> Create new stanza encoding instance for each thread

- internal/aws/containerinsight/const.go
- internal/aws/containerinsight/utils.go
- internal/aws/k8s/k8sclient/clientset.go
- internal/aws/k8s/k8sclient/deployment.go
- internal/aws/k8s/k8sclient/deployment_info.go
- internal/aws/k8s/k8sclient/deployment_test.go
- internal/aws/k8s/k8sclient/replicaset.go
- internal/aws/k8s/k8sclient/replicaset_info.go
- internal/aws/k8s/k8sclient/replicaset_test.go
- internal/aws/k8s/k8sclient/statefulset.go
- internal/aws/k8s/k8sclient/statefulset_info.go
- internal/aws/k8s/k8sclient/statefulset_test.go
- receiver/awscontainerinsightreceiver/README.md
- receiver/awscontainerinsightreceiver/internal/k8sapiserver/k8sapiserver.go
- receiver/awscontainerinsightreceiver/internal/k8sapiserver/k8sapiserver_test.go
- receiver/awscontainerinsightreceiver/internal/k8sapiserver/leaderelection.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore_test.go
- Add new `status_replicas_available/unavailable` metrics at stateful & replicaset types. 
- Add new `replicas_desired/_ready` metrics for all workload types
- Rename existing metrics that are duplicates of newly added ones
- Drop workload type prefix (`deployment_`) from exisitng status_replicas metrics
- Note that for the service account running the agent/collector pod, the role its bound to should grant list and watch permissions to `apps/replicasets` and `apps/statefulsets`.
**Testing:**
- Update/added unit tests
- Manually tested the changes on a dev cluster. 
**status_replicas_available/_unavailable**
**replicas_desired/_ready**
`Deployment`
```
{
{
[
"ClusterName",
"Namespace",
"PodName"
],
[ …
```
> Add status_replicas_available/_unavailable & replicas_desired/_ready metrics for all workload types

- receiver/awscontainerinsightreceiver/internal/k8sapiserver/prometheus_scraper.go
**Description:** There is a typo in the metric allow list
**Testing:** 
> fix typo in control plane metric allow list

- internal/aws/awsutil/conn.go
- internal/aws/awsutil/shared_config.go
- internal/aws/awsutil/shared_config_test.go
The AWS SDK implementation for getting the user home directory for the default shared config files changed from purely environment variables ([v1.44.106](https://github.com/aws/aws-sdk-go/blob/v1.44.106/internal/shareddefaults/shared_config.go#L33)) to a fallback on getting it from the OS in [more recent versions](https://github.com/aws/aws-sdk-go/blame/v1.44.332/internal/shareddefaults/shared_config.go#L32). This change breaks the credential ordering when running as root with systemd. In the previous version, the environment variables would not resolve properly and would result in the SDK trying to use `.aws/credentials` rather than `/root/.aws/credentials`, which would allow it to fallthrough to the EC2RoleProvider.
Sets the fallback shared config files using the …
> Add fallback shared config files for credential ordering.

- .chloggen/xray-exporter-w3c-id-beta-feature-gate.yaml
- exporter/awsxrayexporter/README.md
- exporter/awsxrayexporter/awsxray_test.go
- exporter/awsxrayexporter/factory.go
- exporter/awsxrayexporter/factory_test.go
Cherry-picking the following commit (scheduled for OTel `v0.86.0` release):
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26553
> [exporter/awsxray] Change exporter.awsxray.skiptimestampvalidation feature gate from Alpha to Beta

- config/confighttp/confighttp.go
- exporter/lokiexporter/factory_test.go
- processor/resourcedetectionprocessor/go.mod
- processor/resourcedetectionprocessor/go.sum
The upstream version of the confighttp package causes issues with apm translations(specifically the `resourcedetectionprocessor` translations):
- The `CustomRoundTripper` field is of type function and thus cannot be marshalled. We omit it from marshalling in this change. 
- The default value for `TLSSetting` for the confighttp package causes a null pointer exception during translation. This change omits it from marshalling if default.
Modified go.mod of the resource detection processor to use our version of the confighttp package.
**Testing:** Unit tests functioning as before
> Modify confighttp and resourcedetection packages to allow for apm translations 

- pkg/stanza/operator/input/tcp/tcp.go
Upstream added a new variable `MultiLineBuilder` which was originally part of the `Multiline` variable that will be omitted if empty. Since `MultiLineBuilder` is a func type, yaml encoder cannot marshal it thus causing issues when creating the yaml file.
**Testing:** 
Relying on unit test. Also tested on agent side.
> Omit MultiLineBuilder variable if empty

- receiver/awscontainerinsightreceiver/internal/stores/podstore.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore_test.go
**Description:** The `node_<cpu|memory>_request` metrics and metrics derived from them (`node_<cpu|memory>_reserved_capacity`) differ from the output of `kubectl describe node <node_name>`. This is because kubectl [filters out terminated pods](https://github.com/kubernetes/kubectl/blob/302f330c8712e717ee45bbeff27e1d3008da9f00/pkg/describe/describe.go#L3624). See linked issue for more details.
Adds a filter for terminated (succeeded/failed state) pods. 
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27262
**Testing:** Added unit test to validate pod state filtering. Built and deployed changes to cluster. Deployed `cpu-test` pod.
The gap is when the change was deployed. The metric can be see spiking up while the `cpu-test` pod is running …
> Filter terminated pods from node request metrics.

- exporter/awscloudwatchlogsexporter/exporter.go
- exporter/awsemfexporter/emf_exporter.go
- exporter/awsemfexporter/emf_exporter_test.go
- internal/aws/cwlogs/cwlog_client.go
- internal/aws/cwlogs/cwlog_client_test.go
Add pulse metadata flag in PLE user-agent in EMF exporter, so CWLogs backend can indicate EMF logs request type for the corresponding actions.
UnitTest
> add pulse metadata flag in PLE user-agent

- .chloggen/aws_exporter_localrootspans.yaml
- exporter/awsxrayexporter/awsxray.go
- exporter/awsxrayexporter/internal/translator/segment.go
- exporter/awsxrayexporter/internal/translator/segment_test.go
Description:
We are adjusting the segment creation to accommodate local root spans.
If a span is a not a local root, then we keep existing behavior.
If it is a local root then:
If it is an Internal or Server span, then promote it to a segment.
Else we will split it into a segment and subsegment. The segment will represent the service operation and the subsegment will represent the dependency (service A calls service B).
Testing:
Unit Testing
Documentation:
None
> Adding segment splits

- exporter/awsxrayexporter/internal/translator/segment.go
- exporter/awsxrayexporter/internal/translator/segment_test.go
In this commit, we are fixing a couple small bugs missed in the previous review. First, we are adding a nil-guard when settting dependencySubsegment.Name, to avoid the (unlikely, but possible) scenario where local root dependency spans are created without awsRemoteService. Second, we are updating the common logic for setting segment.Name, which previously only looked at CLIENT/PRODUCER spans, but now needs to look at CONSUMER spans.
**Link to tracking Issue:** N/A, related to comments on https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/111
**Testing:** make succeeds
**Documentation:** N/A
> Update segment conversion logic

- .chloggen/add-aws-http-error-event.yaml
- exporter/awsxrayexporter/internal/translator/cause.go
- exporter/awsxrayexporter/internal/translator/cause_test.go
- exporter/awsxrayexporter/internal/translator/segment.go
- exporter/awsxrayexporter/internal/translator/segment_test.go
- Convert individual HTTP error events into exceptions within subsegments for AWS SDK spans.
- Normalize the service name from awsxray.AWSServiceAttribute attribute by removing the AWS.SDK. prefix (in some aws sdk instrumentation, we have added the prefix to produce metrics with the prefix to clearly indicate the resource). This change ensures that X-Ray backend recognizes standard service names like "DynamoDb", "S3", etc., enabling correct identification of AWS service types.
**Link to tracking Issue:** NA
**Testing:** Unit tests are added.
**Documentation:** NA
This is a copy of a open PR to open-telemetry/opentelemetry-collector-contrib https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27232. The goal of is this PR is …
> [exporter/awsxray] Add aws sdk http error events to x-ray subsegment and strip prefix AWS.SDK. from aws remote service name

- .chloggen/strip-aws-sdk-local-root.yaml
- exporter/awsxrayexporter/internal/translator/segment.go
- exporter/awsxrayexporter/internal/translator/segment_test.go
- Previous change to strip the prefix in other cases https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27232/commits/7c037ad3022a2d5d0dcb09bf43cde89760fb5f8b
**Description:** Adding logic to strip AWS.SDK from local root dependency spans. This had been done previously for other spans, but there was a missed codepath related to local root naming.
**Link to tracking Issue:** None
**Testing:** Added a unit test
**Documentation:** None
> Add logic for stripping the AWS.SDK prefix for Local Root spans

- exporter/awscloudwatchlogsexporter/exporter.go
- exporter/awsemfexporter/emf_exporter.go
- exporter/awsxrayexporter/awsxray.go
- extension/awsmiddleware/README.md
- extension/awsmiddleware/helper.go
- extension/awsmiddleware/helper_test.go
- extension/awsmiddleware/middleware.go
- extension/awsmiddleware/middleware_test.go
- extension/awsmiddleware/options.go
**Description:** Add an option to pass in the SDK version instead of having separate repeated functions for each.
**Testing:** Added unit tests.
**Documentation:** Updated README.
> [extension/awsmiddleware] Change Configure to take in either SDK version

- extension/awsmiddleware/config.go
- extension/awsmiddleware/middleware.go
- extension/awsmiddleware/middleware_test.go
**Description:** Expose the constructor for the configurer in case it needs to be used outside of the extension context. This isn't the standard usecase.
**Testing:** N/A
**Documentation:** N/A
> [extension/awsmiddleware] Expose NewConfigurer.

- exporter/awsemfexporter/config.go
- exporter/awsemfexporter/config_test.go
- exporter/awsemfexporter/emf_exporter.go
- internal/aws/cwlogs/cwlog_client.go
- internal/aws/cwlogs/cwlog_client_test.go
**Notes: It is only for public preview and DO NOT merge it for private beta build.**
Remove all usages of APM/Pulse in EMF exporter and use AppSignals instead. 
**Testing:** 
Passed unit test.
> [exporter/awsemf] Renaming APM/Pulse to AppSignals

- receiver/awscontainerinsightreceiver/internal/stores/kubeletutil/kubeletclient.go
- receiver/awscontainerinsightreceiver/internal/stores/kubeletutil/kubeletclient_test.go
CloudWatch Agent fails to start within IPv6 EKS clusters by throwing an error while trying to connect to kubelet. This issue affects Container Insights customers with IPv6 clusters. This change adds a check for IPv6 in the kubelet client to handle IPv6 address correctly. 
The Error from agent pod:
```
stream logs failed Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy) for amazo │
│ n-cloudwatch/cloudwatch-agent-xxxxx (cloudwatch-agent) 
```
**Testing:** 
IPv6 Cluster yaml used:
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
name: ipv6
region: us-west-1
version: "1.27"
kubernetesNetworkConfig:
ipFamily: IPv6
addons:
- name: vpc-cni
version: latest
- …
```
> Support IPv6 clusters with Container Insights

- pkg/resourcetotelemetry/README.md
- pkg/resourcetotelemetry/resource_to_telemetry.go
- pkg/resourcetotelemetry/resource_to_telemetry_test.go
**Description:** The `pkg/resourcetotelemetry` exporter helper wraps an exporter and enabling it will copy all attributes from resource metrics to each data point within. Currently, the helper only performs a copy and does not modify the resource attributes, which can result in duplicate attributes in certain exporters (e.g. PRW exporter).
Adds an option to clear the resource attributes after the copy has been completed.
**Testing:** Added unit test to verify behavior.
**Documentation:** Updated README.
> Add option to clear resource attributes after copy

- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/mem_extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/mem_extractor_test.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/k8swindows.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/kubelet.go
1. Added memory extractor at pod and node level
2. Add unit tests for memory extractor
3. use cpu and memory extractor for k8s windows
**Testing**
Unit tests - Passed
Manual tests - 
Ran CW agent on EKS cluster to see following results in metrics section in CW dashboard
CPU and memory utilization metrics for Windows pod `windows-server-jis-Itsc2019`
> Add memory extractors for pod and node level

- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/cpu_extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/cpu_extractor_test.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/extractorhelpers.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/extractorhelpers_test.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/mem_extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/mem_extractor_test.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/kubelet.go
1. Create new structs to represent CPU and memory stats in RawMetric. This removes RawMetric dependency on Kubelet CPU and memory stats.
2. Refactor existing RawMetric struct to use new CPU and memory stats.
3. Add more unit tests for extractorhelpers
4. This refactor helped avoid adding nil verification checks in extractors.
5. This refactoring extends RawMetrics and existing extractors to work for HNSSHIM API responses.
**Testing:** 
1. Unit tests are passing locally.
2. Pod CPU and memory utilization working after refactoring.
> Define structs for CPU and Memory stats

- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/k8swindows.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/kubelet.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/kubelet/client.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/kubelet/kubelet.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/kubelet/kubelet_test.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/kubelet_test.go
Add container level CPU and memory metrics collection
1. Add metric collection at container level
2. Refactor existing kubelet code to make it unit testable.
3. Add units for kubelet to test pod, node and container level metric collection.
**Testing:** 
1. Local unit tests passed correctly.
2. contaner level metrics are visible in CW dashboard
> Add Container level metrics for CPU and memory resources.

- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/extractorhelpers.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/net_extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/net_extractor_test.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/testdata/CurSingleKubeletSummary.json
- receiver/awscontainerinsightreceiver/internal/k8swindows/k8swindows.go
Add network metrics collection at pod and network level
1. Add network extractor to collect bytes received, transmitted and error received and transmitted, total bytes.
2. Network metrics are aggregate of metrics of all interfaces.
3. Added unit tests for network extractor
4. Added version tag in cAdvisorMetric for Windows
1. All newly added unit tests passed for network tests
2. Metrics in CI dashboard at pod and node level
> Add network metrics at pod and network level

- cmd/otelcontribcol/go.mod
- go.mod
- internal/aws/containerinsight/const.go
- internal/aws/containerinsight/utils.go
- internal/aws/containerinsight/utils_test.go
- internal/aws/k8s/go.mod
- internal/aws/k8s/k8sclient/clientset.go
- internal/kubelet/client.go
- internal/kubelet/client_test.go
- internal/kubelet/go.mod
- internal/kubelet/go.sum
1. Added workaround to fix ServiceAccount token and cert path for kubelet account inside HPC.
2. Added workarond to fix above issue in k8s clientset.
**Testing:** 
Tested the changes locally.
1. Works with both as host process container, normal container.
2. Not adding any screenshot since not changing any metrics with this PR.
> Enable awscontainerinsights receiver to run inside Host Process container

- .chloggen-aws/jmx-update-config.yaml
- receiver/jmxreceiver/config.go
- receiver/jmxreceiver/go.mod
- receiver/jmxreceiver/receiver.go
- receiver/jmxreceiver/receiver_test.go
**Description:** Instead of storing the password in plaintext in the receiver config, provide the option to read it in from a read-restricted file in a Java Properties file format.
**Testing:** Built and tested.
On start up if the file is missing:
```
receivers::jmx: `password_file` is inaccessible: stat /home/ec2-user/jmxremote.password: no such file or directory
```
When file is not read-restricted:
```
receivers::jmx: `password_file` read access must be restricted to owner-only: /home/ec2-user/jmxremote.password
```
If both are valid, then on start up the password will be present in the `jmx-config-*.properties` file, which has 0600 access.
A known issue is that if the file is also being used by the JMX agent and the file has read-write permissions, the JMX agent will hash the …
> Add password file option to JMX config.

- receiver/awscontainerinsightreceiver/internal/host/nodeCapacity.go
- receiver/awscontainerinsightreceiver/internal/host/nodeCapacity_test.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/extractorhelpers.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/fs_extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/fs_extractor_test.go
Windows server 2019 nodes showed CPU utilization above 100 when customer workload is deployed. This patch will fix this issue for Windows.
GetCPUCores returned number of physical cores but this patch will consider virtual cores on machine.
1. Unit tests pass for extractors
2. e2e tests for Windows node worked and CPU utilization is comparative with CPU usage in task manager.
> Fix CPU utilization percentage for Windows nodes

- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/fs_extractor.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/extractors/fs_extractor_test.go
Add fstype and fsdev in ContainerFS metrics. Values for these two tags will be empty.
1. Tested this with integ tests
> Add fstype and fsdev in ContainerFS metrics

- .chloggen-aws/sdk-telemetry-user-agent.yaml
- cmd/configschema/go.mod
- cmd/configschema/go.sum
- cmd/otelcontribcol/go.mod
- cmd/otelcontribcol/go.sum
- exporter/awsemfexporter/emf_exporter.go
- exporter/awsemfexporter/go.mod
- exporter/awsemfexporter/go.sum
- exporter/awsemfexporter/internal/appsignals/useragent.go
- exporter/awsemfexporter/internal/appsignals/useragent_test.go
- go.mod
- go.sum
**Description:** Adds additional user agent if configured for App Signals. Extracts the SDK Telemetry attributes from the resource attributes to build the user agent strings. Uses a TTL cache to keep track of the language/version pairs received by the exporter. 
**Testing:** Built (w/ AWS SDK LogLevel set to `LogDebug`).
```
│ -----------------------------------------------------                                                                                                                                                                                                                                                                                                                  │
│ 2024/02/26 23:05:41 DEBUG: Request logs/PutLogEvents Details: …
```
> [exporter/awsemfexporter] Add app signals specific user agent.

- exporter/awsxrayexporter/internal/translator/segment.go
- exporter/awsxrayexporter/internal/translator/segment_test.go
In the past, we converted all symbolic inputs of annotation key to "_" because the backend don't have the ability to handle other inputs. Now, with the modification of the backend, we can handle input of “.” type. Xray-PM has agreed that this conversion step is no longer necessary for ".", so I made the change here to pass the "." type naming as-is
**Testing:** 
Go Unit test and test a modified CWA in local env, perform as expect
** Note **
We decided to use feature gate to remove the converter from up-stream, the PR link is below
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31386
> Adjust Dot Converter for XRay-Exporter

- internal/aws/proxy/server_test.go
- receiver/awsxrayreceiver/factory_test.go
- receiver/awsxrayreceiver/receiver_test.go
**Description:** A previous PR (https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/174) unified the AWS session creation so the proxy uses the `internal/aws/awsutil` package. The unit tests could not be run at the time.
**Testing:** Ran the unit tests locally.
> [internal/aws/proxy] Fix proxy server unit test.

- receiver/awscontainerinsightreceiver/internal/gpu/dcgmscraper.go
- receiver/awscontainerinsightreceiver/internal/gpu/dcgmscraper_test.go
Add `InstanceType` attribute to GPU metrics
**Testing:** 
Tested on a test cluster. Example EMF entry:
```
{
{
[
"ClusterName"
],
[
"ClusterName",
"InstanceId",
"NodeName"
],
[
"ClusterName",
"GpuDevice",
"InstanceId",
"InstanceType",
"NodeName"
]
],
"Metrics": [
{
"Name": "node_gpu_temperature",
"Unit": "None"
},
{
"Name": "node_gpu_power_draw",
"Unit": "None"
},
{
"Name": "node_gpu_utilization",
"Unit": "Percent"
},
{
"Name": "node_gpu_memory_utilization",
"Unit": "Percent"
},
{
"Name": "node_gpu_memory_used",
"Unit": "Bytes"
},
{
"Name": "node_gpu_memory_total",
"Unit": "Bytes"
}
]
}
],
"ClusterName": "mixed-test",
"GpuDevice": "nvidia0",
"InstanceId": "i-xxxxxxxxxx",
"InstanceType": …
```
> Add InstanceType to GPU metrics

- receiver/awscontainerinsightreceiver/internal/efa/efaSysfs.go
- receiver/awscontainerinsightreceiver/internal/efa/efaSysfs_test.go
- receiver/awscontainerinsightreceiver/receiver.go
If the EFA scraper is enabled but was unable to actually scrape the metrics from disk, then we were getting a nil pointer trying to compute metrics.
**Testing:**
New test before the code change:
```
% go test -count=1 -run TestGetMetricsBeforeSuccessfulScrape ./internal/efa/...
--- FAIL: TestGetMetricsBeforeSuccessfulScrape (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x148a155]
goroutine 6 [running]:
testing.tRunner.func1.2({0x15b57c0, 0x25a1120})
/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0x15b57c0?, …
```
> Re-enable EFA metric collection and fix nil pointer bug.

- go.mod
- go.sum
CloudWatch Agent was flagged for CGO-2024-2611, CVE-2024-24786
https://pkg.go.dev/vuln/GO-2024-2611
We are not impacted by this CVE as we don't have any instances where we are unmarshaling into a message which contains a google.protobuf.Any value, or when the UnmarshalOptions.DiscardUnknown option is set.
That being said, the best thing we can do is to update to the latest and greatest protobuf so we know with certainty we aren't impacted and it will also satisfy scanners
**Testing:** N/A
**Documentation:** N/A
> upgrade protobuf version - GO-2024-2611, CVE-2024-24786

- receiver/awscontainerinsightreceiver/internal/cadvisor/cadvisor_linux.go
cadvisor is throwing an error while decorating metrics with k8s stores. The issue caused the agent pods to go into `CrashLoop` by throwing error in the agent logs:
```
goroutine 1076 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver/internal/cadvisor.(*Cadvisor).GetMetrics(0xc001a80180)
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver@v0.89.0/internal/cadvisor/cadvisor_linux.go:231 +0x461
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver.(*awsContainerInsightReceiver).collectData(0xc000b23d40, {0x4c3b158, 0xc000485ef0})
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver@v0.89.0/receive …
```
> fix nil referencing issue in cadvisor during metric decoration

- receiver/awscontainerinsightreceiver/internal/gpu/dcgmscraper_config.go
- receiver/awscontainerinsightreceiver/internal/k8sapiserver/prometheus_scraper.go
- receiver/awscontainerinsightreceiver/internal/prometheusscraper/simple_prometheus_scraper.go
- add `scrapeProtocals` config for DCGM prometheus scraper
- add ID to simple prometheus scraper settings
With a recent change to prometheus receiver, we need to pass IDs to create a multiple instances of prometheus receivers within the same process (eg. aws CI receiver).
Related ticket: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32123
**Testing:**
Validated with a test cluster that contains both Tranium and NVIDIA instances
> adding scrape protocol and ID for prometheus receiver

- internal/coreinternal/attraction/attraction.go
You can only delete an attribute by key or pattern. We need to delete an attribute only if the key has a specific value. 
N/A
**Testing:** 
Make the change. Take in cwa. Add a delete with service.name removed when value is unknow_service:java
```
2024/05/14 19:23:26 I! Config has been translated into TOML /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml 
2024/05/14 19:23:26 D! config [agent]
collection_jitter = "0s"
debug = true
flush_interval = "1s"
flush_jitter = "0s"
hostname = ""
interval = "60s"
logfile = "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
logtarget = "lumberjack"
metric_batch_size = 1000
metric_buffer_limit = 10000
omit_hostname = false
precision = ""
quiet = false
round_interval = false …
```
> Delete Attribute By Key And Value

- receiver/jmxreceiver/supported_jars.go
Take latest release version of JMX gather jar hash as valid
N/A
**Testing:** 
N/A
**Documentation:** 
N/A
> Support Latest Released Jar Of JMX metrics gatherer

- internal/aws/containerinsight/const.go
- internal/kubelet/client.go
- receiver/awscontainerinsightreceiver/internal/k8swindows/kubelet/client.go
- receiver/awscontainerinsightreceiver/internal/stores/kubeletutil/kubeletclient.go
- receiver/awscontainerinsightreceiver/internal/stores/kubeletutil/kubeletclient_test.go
- receiver/awscontainerinsightreceiver/internal/stores/localnode.go
- receiver/awscontainerinsightreceiver/internal/stores/localnode_test.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore.go
- receiver/awscontainerinsightreceiver/internal/stores/store.go
- receiver/awscontainerinsightreceiver/receiver.go
**Description:** In some cases (systemd), kubelet isn't available on collector start up. Instead of failing and stopping the collector, return nil and wait for kubelet to be available and initialize the rest of the receiver after.
Behavior matches the [collector](https://github.com/open-telemetry/opentelemetry-collector/blob/5cbf8bebe4ad757f01974e9c65b853ddb7b28bba/component/component.go#L31-L42) recommendation for long-running starting operations. 
```go
// Start tells the component to start. Host parameter can be used for communicating
// with the host after Start() has already returned. If an error is returned by
// Start() then the collector startup will be aborted.
// If this is an exporter component it may prepare for exporting
// by connecting to the endpoint.
//
// If the …
```
> Add kubelet availability check for systemd CI.

- exporter/awsxrayexporter/README.md
- exporter/awsxrayexporter/internal/translator/aws.go
- exporter/awsxrayexporter/internal/translator/aws_test.go
This commit is to allow users to set multiple log group names or arns using environmental variable. We choose to use `&` to separate individual log group name or arn because `&` is not allowed in log group names (https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateLogGroup.html) and `&` implicitly means 'AND'. 
N/A
Unit tests.
Manual end 2 end test confirmed that we get 2 log groups in the raw trace with the change. Note the `cloudwatch_logs` field below:
```
{
"Id": "1-667339a9-c872ab16dbc29a0c11b60c8d",
"Duration": 0.001,
"LimitExceeded": false,
"Segments": [
{
"Id": …
```
> allow multiple log group names/arns to be set in environmental variables for xray exporter

- receiver/jmxreceiver/supported_jars.go
**Description:** Updates the set of supported OTEL JMX Gatherer versions to include a build until the fix has been accepted and released by OTEL.
**Testing:** See https://github.com/aws/amazon-cloudwatch-agent/pull/1240 for testing.
> Add hash for OTEL JMX Gatherer JAR with Tomcat metrics fix

- internal/aws/containerinsight/const.go
- internal/aws/containerinsight/utils_test.go
- internal/aws/k8s/k8sclient/node.go
- internal/aws/k8s/k8sclient/node_info.go
- internal/aws/k8s/k8sclient/node_test.go
- internal/aws/k8s/k8sclient/pod.go
- internal/aws/k8s/k8sclient/pod_info.go
- internal/aws/k8s/k8sclient/pod_test.go
- internal/aws/k8s/k8sutil/util.go
- internal/aws/k8s/k8sutil/util_test.go
- receiver/awscontainerinsightreceiver/config.go
- receiver/awscontainerinsightreceiver/internal/k8sapiserver/k8sapiserver.go
- receiver/awscontainerinsightreceiver/internal/k8sapiserver/k8sapiserver_test.go
- receiver/awscontainerinsightreceiver/internal/k8sapiserver/utils.go
- receiver/awscontainerinsightreceiver/internal/stores/nodeinfo.go
- receiver/awscontainerinsightreceiver/internal/stores/nodeinfo_test.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore.go
- receiver/awscontainerinsightreceiver/internal/stores/podstore_test.go
- receiver/awscontainerinsightreceiver/internal/stores/store.go
- receiver/awscontainerinsightreceiver/internal/stores/utils.go
- receiver/awscontainerinsightreceiver/internal/stores/utils_test.go
- receiver/awscontainerinsightreceiver/receiver.go
https://github.com/amazon-contributing/opentelemetry-collector-contrib/pull/214 introduced NVIDIA GPU count metrics to track request, limit & usage counts at a pod, node & cluster level. However, this implementation was scraping all the metrics from the leader node for the entire cluster and introducing new log events of `PodGPU` Type.
This change moves the scraping of these metrics into the pod store such that they are scraped on each agent/collector pod as opposed to just the leader and they are now emitted as part of the existing Type `Pod` and Type `Node` log events (similar to the cpu & mem metrics).
This change also tweaks the metrics to more closely match the cpu metrics. 
* Rename (pod|node)_gpu_total -> (pod|node)_gpu_usage_total
* Add …
> Move GPU metrics for request, limit, usage & reserved_capacity into pod store

- internal/aws/containerinsight/utils.go
- receiver/awscontainerinsightreceiver/internal/k8sapiserver/k8sapiserver_test.go
**Description:** Update the hyper_pod_* metric names after consultation with the Sagemaker HyperPod team.
**Testing:** Built a custom image and deployed on a Cluster to Test.
> Updating hyper_pod_* metric names to hyperpod_*

- processor/resourcedetectionprocessor/internal/aws/eks/detector.go
- processor/resourcedetectionprocessor/internal/aws/eks/detector_test.go
**Description:** If `newK8sDetectorUtils` encounters an error, it will return a nil util and an error. Currently, the error is never logged and the detector is created. When the `Detect` function is called, the nil util is passed into the function and a nil panic occurs.
Changed the constructor function to return the error if the util constructor fails.
**Testing:**  Updated unit tests.
> [processor/resourcedetection] Fix EKS detector nil panic.

- receiver/awscontainerinsightreceiver/internal/neuron/neuron_monitor_scraper_config.go
- receiver/awscontainerinsightreceiver/internal/neuron/neuron_monitor_scraper_test.go
- receiver/awscontainerinsightreceiver/internal/prometheusscraper/simple_prometheus_scraper.go
- receiver/awscontainerinsightreceiver/internal/prometheusscraper/simple_prometheus_scraper_test.go
PR to fix NeuronMonitor, NeuronMonitor depends on IMDS and wont be able to set instanceId and NodeName  from inside the hyperpod  instances, so we are removing dependency of populating the Instance dimension away from Prom labe
**Testing:**
Hyperpod metrics being published
> Use HostInfo to populate instanceId, InstanceType

- processor/resourcedetectionprocessor/internal/aws/eks/detector.go
- processor/resourcedetectionprocessor/internal/aws/eks/detector_test.go
**Description:** Instead of erroring out in the constructor, log the error as a debug log and make the `Detect` function a no-op. Similar to `ecs` detector https://github.com/amazon-contributing/opentelemetry-collector-contrib/blob/76facad52e8fc5e32459d1023eef9e64608ddb6b/processor/resourcedetectionprocessor/internal/aws/ecs/ecs.go#L52-L55
**Testing:** Updated unit tests.
> [processor/resourcedetection] Make detect no-op for non-EKS environments

- exporter/awsemfexporter/metric_translator.go
- exporter/awsemfexporter/metric_translator_test.go
- exporter/awsemfexporter/util_test.go
- internal/aws/cwlogs/cwlog_client_test.go
**Description:** Attach AwsAccountId as a KeyAttribute for Compass Entity. The exporter assumes this is already set as a resource attribute earlier in the pipeline.
**Testing:** Updated unit tests
> Attach AwsAccountId as a KeyAttribute for Compass Entity

- exporter/awsxrayexporter/awsxray.go
- exporter/awsxrayexporter/awsxray_test.go
- exporter/awsxrayexporter/config.go
This PR adds a configuration `transit_spans_in_otlp_format` in X-Ray Exporter to allow customers to choose to send spans in otlp format. 
**Testing:** 
unit-tests done.
tested with cloudwatch agent, by running a sample app in EKS and verified the data received in X-Ray contains `aws.xray.exporter.config.index_all_attributes` and `aws.xray.exporter.config.indexed_attributes`. 
```
{
"resource": {
"attributes": {
"service.name": "nginx-proxy",
"cloud.region": "sa-east-1",
"host.image.id": "ami-05bf16341c7ebb2e4",
"host.type": "m5.large",
"ec2.tag.aws:autoscaling:groupName": "eks-ng-23d4a773-82c9130c-e74b-0945-e092-86ea527a4e35",
"cloud.availability_zone": "sa-east-1a",
"telemetry.sdk.name": "opentelemetry",
"aws.xray.exporter.config.index_all_attributes": false, …
```
> [awsxrayexporter] Allow sending spans in otlp format with a new config

- exporter/awsemfexporter/metric_translator.go
- exporter/awsemfexporter/metric_translator_test.go
- exporter/awsemfexporter/util.go
- exporter/awsemfexporter/util_test.go
**Description:** Prior to this change, a customer could theoriically export a dimension with an unsupported entity field, such as `com.amazonaws.cloudwatch.entity.internal.foo.bar`. This PR will now drop all fields that begin with `com.amazonaws.cloudwatch.entity.internal`, regardless of validity.
**Testing:** Unit tests
> Drops all attributes with entity prefix in awsemfexporter

- internal/aws/k8s/k8sclient/clientset.go
This MR is a part of effort to elevate single eks cluster performance by migrating the EKS components to use protobuf instead of json.
Modify kubeconfig type to use content type `application/vnd.kubernetes.protobuf` instead of json for performance gain.
> use protobuf content type instead of json for k8s client

- receiver/prometheusreceiver/config.go
Missing marshaler in prometheus receiver causes failures during data translation with yaml tags used for prometheus config. 
> Add marshaler to prometheus receiver config 

- receiver/prometheusreceiver/targetallocator/manager.go
If the CloudWatch Agent Collector pod starts before the Target Allocator pod, it will fail to ping the Target Allocator.  This failure causes the Agent's target allocator thread to end, resulting in prometheus metrics being lost. Currently, the only solution is to restart the pods if this happens.
To overcome this , I removed the `return failure` on Start of the TA Manager thread; thus, TA Manager can keep on trying. 
This ensures no loss in metrics. This also has no extra cost since if the `scrape_config`(savedHash) is the same as the previous one, sync function will immediately return. In the case if the ping keeps failing the `savedHash` will be the same the as the hash--which is 0,   requiring  no extra computing power.  
**Testing:** …
> [Fix] Target Allocator Manager quits if the initial sync fails

- receiver/awscontainerinsightreceiver/internal/gpu/dcgmscraper_config.go
- receiver/awscontainerinsightreceiver/internal/neuron/neuron_monitor_scraper_config.go
- receiver/awscontainerinsightreceiver/receiver.go
For some edge cases, DCGM or Neuron metrics for ContainerInsights are missing host metadata labels including `InstanceId` and/or `InstanceType`. This PR is to use localNode decorator instead `k8sDecorator` to inject those host metadata while processing metrics. 
**Testing:** 
Tested on a test cluster to verify those metadata are still coming as part of DCGM/Neuron EMF logs (some sections have been redacted)
```
{
{
[
"ClusterName"
],
[
"ClusterName",
"Namespace"
],
[
"ClusterName",
"Namespace",
"PodName"
],
[
"ClusterName",
"FullPodName",
"Namespace",
"PodName"
],
[
"ClusterName",
"FullPodName",
"GpuDevice",
"Namespace",
"PodName"
]
],
"Metrics": [
{
"Name": …
```
> use localNode decorator for DCGM and Neuron metrics for host metadata
